#!/usr/bin/env python

Import('env')
Import('env_modules')

env_tove = env_modules.Clone()

env_tove.add_source_files(env.modules_sources, "*.cpp")

env_tove.add_source_files(env.modules_sources, "tove2d/src/cpp/*.cpp")
env_tove.add_source_files(env.modules_sources, "tove2d/src/cpp/mesh/*.cpp")
env_tove.add_source_files(env.modules_sources, "tove2d/src/cpp/shader/*.cpp")
env_tove.add_source_files(env.modules_sources, "tove2d/src/cpp/gpux/*.cpp")
env_tove.add_source_files(env.modules_sources, "tove2d/src/thirdparty/*.cpp")
env_tove.add_source_files(env.modules_sources, "tove2d/src/thirdparty/polypartition/src/*.cpp")

import os 
dir_path = Dir('.').abspath

env_tove.Append(CXXFLAGS=[
    '-std=c++11',
    '-DTOVE_GODOT',
    '-I' + os.path.join(dir_path, 'tove2d/src/thirdparty/fp16/include')])
